using System.Windows;
using System.Windows.Media;
using RGDSCapture.Core;

namespace RGDSCapture.Services
{
    /// <summary>
    /// Swaps the active theme dictionary at runtime. The palette is always
    /// merged dictionary index 0 (see App.xaml); control styles in
    /// Controls.xaml reference colors via DynamicResource, so everything
    /// restyles live with no restart.
    ///
    /// Palettes are generated by <see cref="PaletteBuilder"/> rather than
    /// loaded from disk — Themes/Dark.xaml only exists as the design-time and
    /// pre-startup fallback.
    /// </summary>
    public static class ThemeService
    {
        public static ThemePreset Current { get; private set; } = ThemeCatalog.Default;

        /// <summary>Accent override in force, or null when using the preset's own accent.</summary>
        public static Color? CustomAccent { get; private set; }

        public static void Apply(ThemePreset preset, Color? accentOverride = null)
        {
            var dict = PaletteBuilder.Build(preset, accentOverride);

            var merged = Application.Current.Resources.MergedDictionaries;
            if (merged.Count > 0) merged[0] = dict;
            else merged.Add(dict);

            Current = preset;
            CustomAccent = accentOverride;
        }

        /// <summary>Applies the theme recorded in settings, tolerating stale ids.</summary>
        public static void ApplyFrom(AppSettings settings)
        {
            var preset = ThemeCatalog.Resolve(settings.ThemeId);

            Color? accent = null;
            if (!string.IsNullOrWhiteSpace(settings.CustomAccent))
                accent = PaletteBuilder.ParseHex(settings.CustomAccent);

            Apply(preset, accent);
        }

        /// <summary>The accent actually in effect — the override if set, else the preset's.</summary>
        public static Color EffectiveAccent =>
            CustomAccent ?? PaletteBuilder.ParseHex(Current.Accent);
    }
}
