#!/usr/bin/env python3
"""Generate Resources/icon.ico (and a PNG preview) for RGDSCapture.

The icon is drawn rather than hand-edited so it stays reproducible: run
this on any box with Python and Pillow (no Windows-only image editor in
the pipeline) and the committed .ico is regenerated byte-for-byte.

    pip install Pillow
    python tools/generate_icon.py

The mark is the RG DS silhouette - two stacked screens lit in the app
accent - with a record dot set into the lower one. Three shapes and no
lettering, because the 16x16 taskbar size is the one that has to work;
anything finer than this turns to mud once Windows resamples it.
"""

from __future__ import annotations

import argparse
import struct
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

# Canvas the artwork is drawn at before it is resampled down to each
# icon size. Everything below is expressed in these units.
S = 1024

# Palette lifted from Themes/Dark.xaml so the icon matches the app.
BG_TOP = (26, 33, 48)        # lighter head of the backdrop gradient
BG_BOTTOM = (10, 12, 16)     # ~VideoAreaBg #0A0B0D
BORDER = (58, 69, 92)        # a touch above BorderStrong #333945
GLOW = (76, 141, 255)        # AccentBg #4C8DFF
SCREEN_TOP_HI = (140, 182, 255)
SCREEN_TOP_LO = (66, 130, 245)
SCREEN_BOT_HI = (76, 141, 255)
SCREEN_BOT_LO = (40, 85, 173)
REC_HI = (255, 90, 90)
REC_LO = (194, 43, 43)       # RecordingBg #C22B2B

# Sizes Windows actually asks for, smallest first. 16 is the taskbar and
# title bar, 32 the desktop, 48 Explorer's medium view, 256 the large one.
ICO_SIZES = (16, 24, 32, 48, 64, 96, 128, 256)

# Only the 256 entry is stored as PNG. Everything below it goes in as an
# uncompressed DIB, which is the layout every icon editor emits and the
# one Inno Setup's SetupIconFile is happiest with - some versions reject
# an .ico whose small entries are PNG-compressed.
PNG_FROM = 256


def vertical_gradient(size: tuple[int, int], top: tuple, bottom: tuple) -> Image.Image:
    """A 1px-wide gradient stretched to size - cheaper than per-pixel work."""
    w, h = size
    strip = Image.new("RGB", (1, h))
    px = strip.load()
    for y in range(h):
        t = y / max(h - 1, 1)
        px[0, y] = tuple(round(a + (b - a) * t) for a, b in zip(top, bottom))
    return strip.resize((w, h), Image.Resampling.BILINEAR)


def rounded_mask(size: tuple[int, int], radius: int, supersample: int = 4) -> Image.Image:
    """Antialiased rounded-rectangle mask, drawn big and scaled down."""
    w, h = size
    big = Image.new("L", (w * supersample, h * supersample), 0)
    ImageDraw.Draw(big).rounded_rectangle(
        (0, 0, w * supersample - 1, h * supersample - 1),
        radius=radius * supersample,
        fill=255,
    )
    return big.resize((w, h), Image.Resampling.LANCZOS)


def ellipse_mask(size: int, supersample: int = 4) -> Image.Image:
    big = Image.new("L", (size * supersample, size * supersample), 0)
    ImageDraw.Draw(big).ellipse((0, 0, size * supersample - 1, size * supersample - 1), fill=255)
    return big.resize((size, size), Image.Resampling.LANCZOS)


def paste_panel(canvas, box, radius, top, bottom):
    """Drop a rounded, vertically graded panel onto the canvas."""
    x0, y0, x1, y1 = box
    w, h = x1 - x0, y1 - y0
    panel = vertical_gradient((w, h), top, bottom).convert("RGBA")
    canvas.paste(panel, (x0, y0), rounded_mask((w, h), radius))


def panel_mask(x0: int, y0: int, w: int, h: int, r: int) -> Image.Image:
    """Full-canvas mask holding a single screen panel."""
    mask = Image.new("L", (S, S), 0)
    mask.paste(rounded_mask((w, h), r), (x0, y0))
    return mask


def draw_artwork() -> Image.Image:
    icon = Image.new("RGBA", (S, S), (0, 0, 0, 0))

    # --- backdrop: rounded app tile -------------------------------------
    tile_radius = round(S * 0.225)
    backdrop = vertical_gradient((S, S), BG_TOP, BG_BOTTOM).convert("RGBA")
    tile_mask = rounded_mask((S, S), tile_radius)
    icon.paste(backdrop, (0, 0), tile_mask)

    # Accent bloom behind the screens - reads as the panels casting light.
    bloom = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    ImageDraw.Draw(bloom).ellipse(
        (round(S * 0.10), round(S * 0.02), round(S * 0.90), round(S * 0.62)),
        fill=GLOW + (70,),
    )
    bloom = bloom.filter(ImageFilter.GaussianBlur(S * 0.11))
    bloom.putalpha(Image.composite(bloom.getchannel("A"), Image.new("L", (S, S), 0), tile_mask))
    icon.alpha_composite(bloom)

    # Hairline edge so the tile keeps its shape on a dark desktop.
    edge = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    ImageDraw.Draw(edge).rounded_rectangle(
        (3, 3, S - 4, S - 4), radius=tile_radius - 3, outline=BORDER + (235,), width=7
    )
    icon.alpha_composite(edge)

    # --- the two screens ------------------------------------------------
    sw, sh, gap = 470, 336, 86
    left = (S - sw) // 2
    block_h = sh * 2 + gap
    y0 = (S - block_h) // 2
    r = 58

    panels = (
        (y0, SCREEN_TOP_HI, SCREEN_TOP_LO),
        (y0 + sh + gap, SCREEN_BOT_HI, SCREEN_BOT_LO),
    )

    for top_y, hi, lo in panels:
        # Soft drop shadow lifts the panel off the backdrop.
        shadow = Image.new("RGBA", (S, S), (0, 0, 0, 0))
        shadow.paste(Image.new("RGBA", (sw, sh), (0, 0, 0, 150)),
                     (left, top_y + 18), rounded_mask((sw, sh), r))
        icon.alpha_composite(shadow.filter(ImageFilter.GaussianBlur(14)))
        paste_panel(icon, (left, top_y, left + sw, top_y + sh), r, hi, lo)

    # One diagonal sheen across the upper screen, clipped to its corners.
    sheen = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    ImageDraw.Draw(sheen).polygon(
        [(left, y0 + 214), (left + sw, y0 + 104), (left + sw, y0), (left, y0)],
        fill=(255, 255, 255, 42),
    )
    sheen.putalpha(Image.composite(
        sheen.getchannel("A"), Image.new("L", (S, S), 0),
        panel_mask(left, y0, sw, sh, r)))
    icon.alpha_composite(sheen)

    # --- record dot ------------------------------------------------------
    d = 142
    cx = S // 2
    cy = y0 + sh + gap + sh // 2

    # The dark ring is what keeps the red legible against the blue panel
    # once the whole thing is 16 pixels wide.
    ring = d + 34
    icon.paste(Image.new("RGBA", (ring, ring), BG_BOTTOM + (255,)),
               (cx - ring // 2, cy - ring // 2), ellipse_mask(ring))
    dot = vertical_gradient((d, d), REC_HI, REC_LO).convert("RGBA")
    icon.paste(dot, (cx - d // 2, cy - d // 2), ellipse_mask(d))

    return icon


def encode_dib(frame: Image.Image) -> bytes:
    """A 32bpp icon frame: BITMAPINFOHEADER + BGRA rows + empty AND mask.

    Two quirks of icons-in-DIB form, both of which Windows insists on:
    biHeight is written as twice the real height (it covers the colour
    rows plus the mask rows), and the 1bpp AND mask still has to be there
    even though a 32bpp frame carries its transparency in the alpha
    channel. Leaving it out is what produces icons with black corners in
    the odd legacy shell surface, so the mask is written as all zeros.
    """
    w, h = frame.size

    buf = BytesIO()
    frame.save(buf, "dib")
    dib = buf.getvalue()

    # Patch biHeight (bytes 8..12 of the 40-byte header) to h * 2.
    dib = dib[:8] + struct.pack("<i", h * 2) + dib[12:]

    # AND mask: 1 bit per pixel, each row padded out to a 4-byte boundary.
    mask_stride = ((w + 31) // 32) * 4
    return dib + b"\x00" * (mask_stride * h)


def write_ico(art: Image.Image, path: Path) -> None:
    """Write a multi-resolution .ico, resampling art down to each size."""
    payloads = []
    for size in ICO_SIZES:
        frame = art.resize((size, size), Image.Resampling.LANCZOS)
        if size >= PNG_FROM:
            buf = BytesIO()
            frame.save(buf, "png")
            payloads.append((size, buf.getvalue()))
        else:
            payloads.append((size, encode_dib(frame)))

    # ICONDIR, then one 16-byte ICONDIRENTRY per image, then the payloads.
    header = struct.pack("<HHH", 0, 1, len(payloads))
    offset = len(header) + 16 * len(payloads)

    directory = b""
    for size, payload in payloads:
        directory += struct.pack(
            "<BBBBHHII",
            size if size < 256 else 0,   # bWidth  (0 means 256)
            size if size < 256 else 0,   # bHeight
            0,                           # bColorCount (0 = truecolour)
            0,                           # bReserved
            1,                           # wPlanes
            32,                          # wBitCount
            len(payload),
            offset,
        )
        offset += len(payload)

    path.write_bytes(header + directory + b"".join(p for _, p in payloads))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="Resources/icon.ico", help="path of the .ico to write")
    parser.add_argument("--png", default="docs/icon.png", help="path of the 512px PNG preview")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    art = draw_artwork()

    ico_path = root / args.out
    ico_path.parent.mkdir(parents=True, exist_ok=True)
    write_ico(art, ico_path)
    print(f"wrote {ico_path} ({', '.join(f'{n}x{n}' for n in ICO_SIZES)})")

    if args.png:
        png_path = root / args.png
        png_path.parent.mkdir(parents=True, exist_ok=True)
        art.resize((512, 512), Image.Resampling.LANCZOS).save(png_path)
        print(f"wrote {png_path} (512x512)")


if __name__ == "__main__":
    main()
